<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class AlamatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('kota')->insert(array(
            array('kota' => 'Bantul'),
            array('kota' => 'Yogyakarta'),
            array('kota' => 'Sleman')
        ));

        DB::table('kecamatan')->insert(array(
            array('kecamatan' => 'Srandakan', 'id_kota' => 1),
            array('kecamatan' => 'Sanden', 'id_kota' => 1),
            array('kecamatan' => 'Kretek', 'id_kota' => 1),
            array('kecamatan' => 'Pundong', 'id_kota' => 1),
            array('kecamatan' => 'Bambanglipuro', 'id_kota' => 1),
            array('kecamatan' => 'Pandak', 'id_kota' => 1),
            array('kecamatan' => 'Pajangan', 'id_kota' => 1),
            array('kecamatan' => 'Bantul', 'id_kota' => 1),
            array('kecamatan' => 'Jetis', 'id_kota' => 1),
            array('kecamatan' => 'Imogiri', 'id_kota' => 1),
            array('kecamatan' => 'Dlingo', 'id_kota' => 1),
            array('kecamatan' => 'Banguntapan', 'id_kota' => 1),
            array('kecamatan' => 'Pleret', 'id_kota' => 1),
            array('kecamatan' => 'Piyungan', 'id_kota' => 1),
            array('kecamatan' => 'Sewon', 'id_kota' => 1),
            array('kecamatan' => 'Kasihan', 'id_kota' => 1),
            array('kecamatan' => 'Sedayu', 'id_kota' => 1),
            array('kecamatan' => 'Danurejan', 'id_kota' => 2),
            array('kecamatan' => 'Gedongtengen', 'id_kota' => 2),
            array('kecamatan' => 'Gondokusuman', 'id_kota' => 2),
            array('kecamatan' => 'Gondomanan', 'id_kota' => 2),
            array('kecamatan' => 'Jetis', 'id_kota' => 2),
            array('kecamatan' => 'Kotagede', 'id_kota' => 2),
            array('kecamatan' => 'Kraton', 'id_kota' => 2),
            array('kecamatan' => 'Mantrirejon', 'id_kota' => 2),
            array('kecamatan' => 'Mergangsan', 'id_kota' => 2),
            array('kecamatan' => 'Ngampilan', 'id_kota' => 2),
            array('kecamatan' => 'Pakualaman', 'id_kota' => 2),
            array('kecamatan' => 'Tegalrejo', 'id_kota' => 2),
            array('kecamatan' => 'Umbulharjo', 'id_kota' => 2),
            array('kecamatan' => 'Wirobrajan', 'id_kota' => 2),
            array('kecamatan' => 'Berbah', 'id_kota' => 3),
            array('kecamatan' => 'Cangkringan', 'id_kota' => 3),
            array('kecamatan' => 'Depok', 'id_kota' => 3),
            array('kecamatan' => 'Gamping', 'id_kota' => 3),
            array('kecamatan' => 'Godean', 'id_kota' => 3),
            array('kecamatan' => 'Kalasan', 'id_kota' => 3),
            array('kecamatan' => 'Minggir', 'id_kota' => 3),
            array('kecamatan' => 'Mlati', 'id_kota' => 3),
            array('kecamatan' => 'Moyudan', 'id_kota' => 3),
            array('kecamatan' => 'Ngaglik', 'id_kota' => 3),
            array('kecamatan' => 'Ngemplak', 'id_kota' => 3),
            array('kecamatan' => 'Pakem', 'id_kota' => 3),
            array('kecamatan' => 'Prambanan', 'id_kota' => 3),
            array('kecamatan' => 'Seyegan', 'id_kota' => 3),
            array('kecamatan' => 'Sleman', 'id_kota' => 3),
            array('kecamatan' => 'Tempel', 'id_kota' => 3),
            array('kecamatan' => 'Turi', 'id_kota' => 3)
        ));

        DB::table('desa')->insert(array(
            array('desa' => 'Poncosari', 'id_kecamatan' => 1),
            array('desa' => 'Trimurti', 'id_kecamatan' => 1),
            array('desa' => 'Gadingsari', 'id_kecamatan' => 2),
            array('desa' => 'Gadingharjo', 'id_kecamatan' => 2),
            array('desa' => 'Srigading', 'id_kecamatan' => 2),
            array('desa' => 'Murtigading', 'id_kecamatan' => 2),
            array('desa' => 'Tirtomulyo', 'id_kecamatan' => 3),
            array('desa' => 'Parangtritis', 'id_kecamatan' => 3),
            array('desa' => 'Donotirto', 'id_kecamatan' => 3),
            array('desa' => 'Tirtosari', 'id_kecamatan' => 3),
            array('desa' => 'Tirtoharjo', 'id_kecamatan' => 3),
            array('desa' => 'Seloharjo', 'id_kecamatan' => 4),
            array('desa' => 'Panjangrejo', 'id_kecamatan' => 4),
            array('desa' => 'Srihardono', 'id_kecamatan' => 4),
            array('desa' => 'Sidomulyo', 'id_kecamatan' => 5),
            array('desa' => 'Mulyodadi', 'id_kecamatan' => 5),
            array('desa' => 'Sumbermulyo', 'id_kecamatan' => 5),
            array('desa' => 'Caturharjo', 'id_kecamatan' => 6),
            array('desa' => 'Digusan', 'id_kecamatan' => 6),
            array('desa' => 'Gilangharjo', 'id_kecamatan' => 6),
            array('desa' => 'Triharjo', 'id_kecamatan' => 6),
            array('desa' => 'Wijirejo', 'id_kecamatan' => 6),
            array('desa' => 'Guwosari', 'id_kecamatan' => 7),
            array('desa' => 'Sendangsari', 'id_kecamatan' => 7),
            array('desa' => 'Triwidadi', 'id_kecamatan' => 7),
            array('desa' => 'Bantul', 'id_kecamatan' => 8),
            array('desa' => 'Palbapang', 'id_kecamatan' => 8),
            array('desa' => 'Ringinharjo', 'id_kecamatan' => 8),
            array('desa' => 'Sabdodadi', 'id_kecamatan' => 8),
            array('desa' => 'Trirenggo', 'id_kecamatan' => 8),
            array('desa' => 'Canden', 'id_kecamatan' => 9),
            array('desa' => 'Patalan', 'id_kecamatan' => 9),
            array('desa' => 'Sumberagung', 'id_kecamatan' => 9),
            array('desa' => 'Trimulyo', 'id_kecamatan' => 9),
            array('desa' => 'Girirejo', 'id_kecamatan' => 10),
            array('desa' => 'Imogiri', 'id_kecamatan' => 10),
            array('desa' => 'Karang Tengah', 'id_kecamatan' => 10),
            array('desa' => 'Karangtalun', 'id_kecamatan' => 10),
            array('desa' => 'Kebon Agung', 'id_kecamatan' => 10),
            array('desa' => 'Selopamioro', 'id_kecamatan' => 10),
            array('desa' => 'Sriharjo', 'id_kecamatan' => 10),
            array('desa' => 'Wukirsari', 'id_kecamatan' => 10),
            array('desa' => 'Dlingo', 'id_kecamatan' => 11),
            array('desa' => 'Jatimulyo', 'id_kecamatan' => 11),
            array('desa' => 'Mangunan', 'id_kecamatan' => 11),
            array('desa' => 'Muntuk', 'id_kecamatan' => 11),
            array('desa' => 'Temuwuh', 'id_kecamatan' => 11),
            array('desa' => 'Terong', 'id_kecamatan' => 11),
            array('desa' => 'Tamanan', 'id_kecamatan' => 12),
            array('desa' => 'Jagalan', 'id_kecamatan' => 12),
            array('desa' => 'Singosaren', 'id_kecamatan' => 12),
            array('desa' => 'Wirokerten', 'id_kecamatan' => 12),
            array('desa' => 'Jambidan', 'id_kecamatan' => 12),
            array('desa' => 'Potorono', 'id_kecamatan' => 12),
            array('desa' => 'Baturetno', 'id_kecamatan' => 12),
            array('desa' => 'Banguntapan', 'id_kecamatan' => 12),
            array('desa' => 'Bawuran', 'id_kecamatan' => 13),
            array('desa' => 'Pleret', 'id_kecamatan' => 13),
            array('desa' => 'Segoroyoso', 'id_kecamatan' => 13),
            array('desa' => 'Wonokromo', 'id_kecamatan' => 13),
            array('desa' => 'Wonolelo', 'id_kecamatan' => 13),
            array('desa' => 'Sitimulyo', 'id_kecamatan' => 14),
            array('desa' => 'Srimartani', 'id_kecamatan' => 14),
            array('desa' => 'Srimulyo', 'id_kecamatan' => 14),
            array('desa' => 'Pendowoharjo', 'id_kecamatan' => 15),
            array('desa' => 'Timbulharjo', 'id_kecamatan' => 15),
            array('desa' => 'Bangunharjo', 'id_kecamatan' => 15),
            array('desa' => 'Panggungharjo', 'id_kecamatan' => 15),
            array('desa' => 'Tirtonirmolo', 'id_kecamatan' => 16),
            array('desa' => 'Ngestiharjo', 'id_kecamatan' => 16),
            array('desa' => 'Tamantirto', 'id_kecamatan' => 16),
            array('desa' => 'Bangunjiwo', 'id_kecamatan' => 16),
            array('desa' => 'Argodadi', 'id_kecamatan' => 17),
            array('desa' => 'Argomulyo', 'id_kecamatan' => 17),
            array('desa' => 'Argorejo', 'id_kecamatan' => 17),
            array('desa' => 'Argosari', 'id_kecamatan' => 17),
            array('desa' => 'Bausasran', 'id_kecamatan' => 18),
            array('desa' => 'Tegalpanggung', 'id_kecamatan' => 18),
            array('desa' => 'Suryatmajan', 'id_kecamatan' => 18),
            array('desa' => 'Pringgokusuman', 'id_kecamatan' => 19),
            array('desa' => 'Sosromenduran', 'id_kecamatan' => 19),
            array('desa' => 'Baciro', 'id_kecamatan' => 20),
            array('desa' => 'Demangan', 'id_kecamatan' => 20),
            array('desa' => 'Klitren', 'id_kecamatan' => 20),
            array('desa' => 'Kotabaru', 'id_kecamatan' => 20),
            array('desa' => 'Terban', 'id_kecamatan' => 20),
            array('desa' => 'Ngupasan', 'id_kecamatan' => 21),
            array('desa' => 'Prawirodirjan', 'id_kecamatan' => 21),
            array('desa' => 'Bumijo', 'id_kecamatan' => 22),
            array('desa' => 'Cokrodiningratan', 'id_kecamatan' => 22),
            array('desa' => 'Gowongan', 'id_kecamatan' => 22),
            array('desa' => 'Prenggan', 'id_kecamatan' => 23),
            array('desa' => 'Purbayan', 'id_kecamatan' => 23),
            array('desa' => 'Rejowinangun', 'id_kecamatan' => 23),
            array('desa' => 'Panembahan', 'id_kecamatan' => 24),
            array('desa' => 'Kadipaten', 'id_kecamatan' => 24),
            array('desa' => 'Patehan', 'id_kecamatan' => 24),
            array('desa' => 'Gedongkiwo', 'id_kecamatan' => 25),
            array('desa' => 'Suryodiningratan', 'id_kecamatan' => 25),
            array('desa' => 'Mantrirejon', 'id_kecamatan' => 25),
            array('desa' => 'Brontokusuman', 'id_kecamatan' => 26),
            array('desa' => 'Keparakan', 'id_kecamatan' => 26),
            array('desa' => 'Wirogunan', 'id_kecamatan' => 26),
            array('desa' => 'Ngampilan', 'id_kecamatan' => 27),
            array('desa' => 'Notoprajan', 'id_kecamatan' => 27),
            array('desa' => 'Gunungketur', 'id_kecamatan' => 28),
            array('desa' => 'Purwokinanti', 'id_kecamatan' => 28),
            array('desa' => 'Bener', 'id_kecamatan' => 29),
            array('desa' => 'Tegalrejo', 'id_kecamatan' => 29),
            array('desa' => 'Karangwaru', 'id_kecamatan' => 29),
            array('desa' => 'Kricak', 'id_kecamatan' => 29),
            array('desa' => 'Pandeyan', 'id_kecamatan' => 30),
            array('desa' => 'Sorosutan', 'id_kecamatan' => 30),
            array('desa' => 'Giwangan', 'id_kecamatan' => 30),
            array('desa' => 'Warungboto', 'id_kecamatan' => 30),
            array('desa' => 'Mujamuju', 'id_kecamatan' => 30),
            array('desa' => 'Semaki', 'id_kecamatan' => 30),
            array('desa' => 'Tahunan', 'id_kecamatan' => 30),
            array('desa' => 'Pakuncen', 'id_kecamatan' => 31),
            array('desa' => 'Patangpuluhan', 'id_kecamatan' => 31),
            array('desa' => 'Wirobrajan', 'id_kecamatan' => 31),
            array('desa' => 'Jogotirto', 'id_kecamatan' => 32),
            array('desa' => 'Kalitirto', 'id_kecamatan' => 32),
            array('desa' => 'Sendangtirto', 'id_kecamatan' => 32),
            array('desa' => 'Tegaltirto', 'id_kecamatan' => 32),
            array('desa' => 'Argomulyo', 'id_kecamatan' => 33),
            array('desa' => 'Glagaharjo', 'id_kecamatan' => 33),
            array('desa' => 'Kepuharjo', 'id_kecamatan' => 33),
            array('desa' => 'Wukisari', 'id_kecamatan' => 33),
            array('desa' => 'Umbulharjo', 'id_kecamatan' => 33),
            array('desa' => 'Caturtunggal', 'id_kecamatan' => 34),
            array('desa' => 'Condongcatur', 'id_kecamatan' => 34),
            array('desa' => 'Maguwoharjo', 'id_kecamatan' => 34),
        ));
    }
}
